### ISSUE TITLE
Remove additional sign-in required for InstiGo Bug Bounty

### ISSUE THREAD

**Issue by sonusourav** [oss2019/instigo-android#14]
**Is your feature request related to a problem? Please describe.**
When a user tries to give Feedback for Bug-Bounty in the Feedback tab, Google sign-in is required even if user is logged in through google sign-in.

**Describe the solution you'd like**
For those signed-in through google sign in, implement a method to remove the requirement to sign in again to fill the form.

**Screenshot**
![Feedback](https://user-images.githubusercontent.com/34706326/59140501-f42d2600-89bb-11e9-950d-8540f203ec99.jpeg)

**Describe alternatives you've considered**
If possible, think of some way to generalize this for both email & password and google login so that additional login for filling google form is not required.

**Comment by rob729** [comment]
@sonusourav I think the best approach for this problem will be to use an intent to a browser from where the user can fill the feedback form.
What do you think?

**Comment by sonusourav** [comment]
That is definitely one way which is already there on the Setting page in the app. But I wanted it to be in a web view within the app only such that users don't have to sign in again.

**Comment by sonusourav** [comment]
But the thing is you need to do it once even if you log out or change the user account you used to login InstiGo or log in using google or email & password.

**Comment by kushsaini10** [comment]
The Sign-in required issue in WebView is fixed by using - Chrome Custom Tabs - https://developer.chrome.com/multidevice/android/customtabs

This will automatically login the default user logged into the device.
