### ISSUE TITLE
Add shimmer animation to recycler views

### ISSUE THREAD

**Issue by sonusourav** [oss2019/instigo-android#17]
**Is your feature request related to a problem? Please describe.**
Using a **progress bar** to show loading status in recycler views does not reflect good user experience. 

**Describe the solution you'd like**
Add shimmer animation similar to how Facebook does, using their library.
Refer to this tutorial for implementing this 
https://medium.com/mindorks/android-design-shimmer-effect-fa7f74c68a93

**Comment by rob729** [comment]
@sonusourav I would like to work on this issue.

**Comment by sonusourav** [comment]
@rob729 go ahead

**Comment by rob729** [comment]
@sonusourav Can you specify in which activity you want to add this feature?

**Comment by sonusourav** [comment]
Wherever recycler view or list view is there.
