### ISSUE TITLE
Add internet connectivity check methods

### ISSUE THREAD

**Issue by sonusourav** [oss2019/instigo-android#19]
**Is your feature request related to a problem? Please describe.**
If the internet connection is not present or suddenly goes while loading, the progress bar is displayed for an infinite time.

**Describe the solution you'd like**
Add internet check methods across the app. For progress dialogs, keep a timeout of 15 seconds. Also when the internet goes suddenly while loading, display a Snack Bar showing **No internet Connection**.

**Describe alternatives you've considered**
Soon, caching would be added which would support to solve this issue.

**Comment by fzd370** [comment]
I would like to work on this. Can I go ahead?

**Comment by sonusourav** [comment]
> 
> 
> I would like to work on this. Can I go ahead?

Go ahead.

**Comment by gouri-panda** [comment]
@sonusourav  Can I work on this issue? :)

**Comment by sonusourav** [comment]
I guess @fzd370 is not working now, so go ahead

**Comment by fzd370** [comment]
@sonusourav I am. My exams are going on. So I'm getting very little time for all this. I installed the app and tried to login with my google account but it keeps on showing pop-up with "logging" message. If I try to login in after registering it shows error "Please enter a valid key". Do you know what is the problem? Btw cool splash screen.

**Comment by gouri-panda** [comment]
@fzd370 Did you add SHA fingerprint in the firebase project. Check the README file and add the SHA Fingerprint of your app to the firebase project.
