### ISSUE TITLE
Gif on splash screen does not render properly

### ISSUE THREAD

**Issue by sonusourav** [oss2019/instigo-android#3]
**Describe the bug**
The gif pauses for a few seconds before the next screen is shown, which is not good user experience.

**To Reproduce**
1. Open InstiGo app.
2. Observer when the splash screen is there.

**Expected behavior**
The animation must not lag and the transition from splash screen to other screens should be smooth.

**Screenshots**
![gif_lags](https://user-images.githubusercontent.com/34706326/57055188-53aa5e80-6cb7-11e9-9024-692e55d1a1bf.gif)

**Smartphone (please complete the following information):**
 - Device: Redmi 4
 - OS: Andorid Nougat 7.1
 - Version: Build 1.0.0

**Comment by rob729** [comment]
<a href="https://imgflip.com/gif/34nbj5"><img src="https://i.imgflip.com/34nbj5.gif" title="made at imgflip.com"/></a>
@sonusourav Is this much delay fine?

**Comment by sonusourav** [comment]
@rob729 the delay in your device may not be the same as in mine. I could only confirm if you open a PR.
