### ISSUE TITLE
No Notification in Android 9 related mess

### ISSUE THREAD

**Issue by Anshul1507** [oss2019/instigo-android#34]
**Describe the bug**
Regular notification is not showing in android version 9. 

**Smartphone (please complete the following information):**
 - Device: [e.g.  Google Pixel Emulator]
 - OS: [e.g. Android 9]

**Additional context**
I tested in android 7.0, it is working fine.

**Comment by sonusourav** [comment]
Could you share any screenshot or gif?

**Comment by Anshul1507** [comment]
Check my another issue, if your background service not running in bg in android>7, then there is no notification comes regarding mess

**Comment by kushsaini10** [comment]
This issue was arising because Notification channels were not implemented, which are mandatory to display notifications in devices with Android Oreo and above. I have created  a pull request #36 for this.

**Comment by Anshul1507** [comment]
@kushsaini10 Yeah that is another thing , but the main bug in the app is team use only service for bg task instead of they have  to implement this feature with the help of  only Work Manager or Job-Scheduler that is only supported for bg task for android >8.0 in official doc. of android.

**Comment by kushsaini10** [comment]
@Anshul1507 Can you point me where is this bg task written in the app.

**Comment by Anshul1507** [comment]
I mean alarm manager service as bg service for regular notification on a mess time
