### ISSUE TITLE
Settings theme does not match with app's theme

### ISSUE THREAD

**Issue by sonusourav** [oss2019/instigo-android#5]
**Describe the bug**
White text is used over black background in Settings while its opposite in other screens of the app

**To Reproduce**
1. Go to Settings screen
2. Observe the difference

**Expected behavior**
Black text should be used in white background.

**Screenshots**
![settings_theme](https://user-images.githubusercontent.com/34706326/57182820-b8d1a000-6ec1-11e9-8d26-880280fc7eaf.jpeg)

**Smartphone (please complete the following information):**
 - Device: Redmi 4
 - OS: Android Nougat

**Comment by shubhamofbce** [comment]
I want to work on this issue?? can I???

**Comment by sonusourav** [comment]
> 
> 
> I want to work on this issue?? can I???

I have assigned you the other issue requested by you. Once, that's done you can take up this.
