### ISSUE TITLE
Redesign Council screen

### ISSUE THREAD

**Issue by sonusourav** [oss2019/instigo-android#6]
**Describe the bug**
Currently the council screen does not look that good. The cards are not of equal dimensions, further they look stretched or diminished.

**To Reproduce**
1. Go to council screen and observe.

**Expected behavior**
All of them should be of equal dimensions and should be redesigned to look good. Even they do not clearly mention what the picture denotes with respect to the council.

**Screenshots**
This is how it looks now:
![council_screen](https://user-images.githubusercontent.com/34706326/57189142-4942cb80-6f28-11e9-8490-326feba7a258.jpeg)

**Smartphone (please complete the following information):**
 - Device: Redmi 4
 - OS: Android Nougat

**Comment by shubhamofbce** [comment]
I want to work on this.. Can I ???

**Comment by sonusourav** [comment]
> 
> 
> I want to work on this.. Can I ???

Sure, go ahead 👍

**Comment by shubhamofbce** [comment]
@sonusourav Can you tell me
I am not from IIT-Dh how can i sinup???
I tried google sign in but it took too long and don't even signed me in

**Comment by sonusourav** [comment]
There is no restriction for students outside of IIT Dharwad to sign up or sign in. 
> I tried to google sign in but it took too long and don't even signed me in

Refer to this https://github.com/oss2019/instigo-android/issues/7#issuecomment-489487526
In short, you have to first create a firebase account. Then create a project with any name but package name to be entered there should be same as that of InstiGo and then download the JSON file provided by Firebase and copy it to InstiGo project folder. Actually, everyone who will work on this project has to copy their own JSON file and replace the existing file. I have updated the readme, have a look at it.

**Comment by shubhamofbce** [comment]
could you please suggest me how can i do all this

**Comment by Siddharth-Singhs** [comment]
@sonusourav  Can I work on this ?

**Comment by sonusourav** [comment]
Sure go ahead

**Comment by Siddharth-Singhs** [comment]
@sonusourav should I change the design or improve this design only

**Comment by sonusourav** [comment]
You can do anything you like

**Comment by prateekcode** [comment]
Hey Sonu, still the design is not improved. I wish to make some changes. First of all, I will share with you my design Mockup and if you agreed to work then I will continue.

**Comment by sonusourav** [comment]
Sure, go ahead

**Comment by prateekcode** [comment]
Hey Sonu, every time
![pushfailed](https://user-images.githubusercontent.com/64659882/83349162-3d565280-a350-11ea-9459-09713b8f0098.png)
 I'm trying to Create Pull Request I get denied, it shows I'm not permitted to do this kind of operation.

**Comment by sonusourav** [comment]
It is because you are trying to push to the Main repo (oss2019/instigo-android) directly. Instead push it to the forked repo ( i.e. prateekcode/instigo-android). On pushing to the forked repo, GitHub will so an option of creating a PR.

**Comment by sonusourav** [comment]
Closed by #40
