### ISSUE TITLE
Trouble with Google Sign In

### ISSUE THREAD

**Issue by bumblebee1998** [oss2019/instigo-android#7]
**Description of the bug**
As the application is run with android studio and the sign in with google button is clicked on the login page, the google sign client opens up. However the sign is never completed by the sign in client and the progress dialog spins on forever.

**To Reproduce**
1. Go to Login Page of the app
2. Click on the Sign In with Google button
3. Choose a Google account

**Expected behavior**
The sign in process should complete and the user should be moved further into the application.

**Screenshots**

![Demonstration](https://user-images.githubusercontent.com/48888131/57198372-a1f97f00-6f8f-11e9-9c9f-2d6f59d0906f.gif)

**Smartphone :**
 - Device: Lenovo K8 Note
 - OS: Android Oreo

**Comment by sonusourav** [comment]
Could you share a GIF for this? It would be easy to observe whats happening.

**Comment by bumblebee1998** [comment]
> Could you share a GIF for this? It would be easy to observe whats happening.

Did that.

**Comment by sonusourav** [comment]
Actually, currently the server being used is Firebase. Firebase provides a google-services.json file which has to be added to project so as to connect the project with it. For getting that json file, it requires SHA-1 fingerprint( it is like an ID for your PC to the Firebase) of the PC and if the PC changes, either we put to add SHA-1 of the new PC( your PC in this case) to my Firebase account or you need to use google-services.json file from your Firebase account. 
If you share the apk through playstore or other sharing apps, then this whole processes is not required but if someone deploys the app using usb cable from some other PC than whose SHA-1 is added to the Firebase account, then above process is required to be done.

Our first task is to shift our server from Firebase to Node.js server which we are currently working on. As of now, what you do is create your Firebase account and delete the old google-services.json file from your project and add your own google-services.json file.

If you want any help on how to do this, let me know.
